name: Start Windows RDP with Ngrok

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
    - name: Download and Setup Ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive ngrok.zip -DestinationPath "$env:USERPROFILE\ngrok"
        $env:Path += ";$env:USERPROFILE\ngrok"
        & "$env:USERPROFILE\ngrok\ngrok.exe" authtoken 2vQVdz7F82brwtpTYKFJbELmqq6_3zsmPpHoBTN7QX13u6JQ4

    - name: Enable RDP and Set Password
      run: |
        net user runneradmin Hapis@1234
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start Ngrok TCP Tunnel (in background)
      run: |
        Start-Process -FilePath "$env:USERPROFILE\ngrok\ngrok.exe" -ArgumentList "tcp 3389" -WindowStyle Hidden
        Start-Sleep -Seconds 10

    - name: Wait and Fetch RDP Address
      shell: pwsh
      run: |
        $maxAttempts = 10
        $attempt = 0
        $success = $false

        while (-not $success -and $attempt -lt $maxAttempts) {
          try {
            $response = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
            $tcpTunnel = $response.tunnels | Where-Object { $_.proto -eq "tcp" }
            if ($tcpTunnel) {
              Write-Host "✅ RDP address: $($tcpTunnel.public_url)"
              $success = $true
            }
          } catch {
            Start-Sleep -Seconds 5
            $attempt++
          }
        }

        if (-not $success) {
          Write-Host "❌ Gagal mendapatkan alamat Ngrok. Pastikan tunnel berjalan."
        }
