name: Start Windows RDP with Ngrok

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Unzip Ngrok
      shell: pwsh
      run: |
        Expand-Archive -Path ngrok.zip -DestinationPath $PWD\ngrok

    - name: Add Ngrok Token
      shell: pwsh
      run: |
        .\ngrok\ngrok.exe authtoken 30dfRbafgrpHHNWBjmEW0yy345z_3Tp1aSYhSfmcQbtYsiw9q

    - name: Start Ngrok in background
      shell: pwsh
      run: |
        Start-Job { .\ngrok\ngrok.exe tcp 3389 } | Out-Null
        Start-Sleep -Seconds 10

    - name: Show Ngrok TCP Address
      shell: pwsh
      run: |
        try {
          $url = (Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels).tunnels[0].public_url
          Write-Host "`n🔗 Ngrok TCP Address: $url"
        } catch {
          Write-Host "`n❌ Gagal mengambil alamat Ngrok. Coba cek apakah ngrok berjalan dengan benar."
        }

    - name: Enable RDP Access
      shell: pwsh
      run: |
        net user runneradmin Hapis@1234
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Write-Host "`n✅ RDP is enabled. Login info:"
        Write-Host "  • Username: runneradmin"
        Write-Host "  • Password: Hapis@1234"
