name: Start Windows RDP with Ngrok

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Unzip Ngrok
      shell: pwsh
      run: |
        Expand-Archive -Path ngrok.zip -DestinationPath $PWD\ngrok

    - name: Add Ngrok Token
      shell: pwsh
      run: |
        .\ngrok\ngrok.exe authtoken 30dfRbafgrpHHNWBjmEW0yy345z_3Tp1aSYhSfmcQbtYsiw9q

    - name: Enable RDP Access
      shell: pwsh
      run: |
        net user runneradmin Hapis@1234
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start Ngrok TCP and Show Address
      shell: pwsh
      run: |
        Write-Host "⏳ Menjalankan Ngrok, tunggu sebentar..."
        .\ngrok\ngrok.exe tcp 3389
