name: Windows RDP via Browser

on: [push]

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download Ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive ngrok.zip -DestinationPath "$env:USERPROFILE\ngrok"
        & "$env:USERPROFILE\ngrok\ngrok.exe" authtoken 2vQVdz7F82brwtpTYKFJbELmqq6_3zsmPpHoBTN7QX13u6JQ4

    - name: Start Ngrok HTTP
      run: |
        Start-Process -FilePath "$env:USERPROFILE\ngrok\ngrok.exe" -ArgumentList "http 8080" -WindowStyle Hidden
        Start-Sleep -Seconds 5

    - name: Setup mini HTTP server
      run: |
        $listener = New-Object System.Net.HttpListener
        $listener.Prefixes.Add("http://*:8080/")
        $listener.Start()
        Write-Host "Server started on port 8080..."

        while ($listener.IsListening) {
          $context = $listener.GetContext()
          $response = $context.Response

          $filePath = "$(Get-Location)\public\index.html"

          if (Test-Path $filePath) {
            $html = Get-Content $filePath -Raw
          } else {
            $html = "<html><body><h1>File public/index.html tidak ditemukan.</h1></body></html>"
          }

          $buffer = [System.Text.Encoding]::UTF8.GetBytes($html)
          $response.ContentLength64 = $buffer.Length
          $response.OutputStream.Write($buffer, 0, $buffer.Length)
          $response.Close()
        }

    - name: Keep alive
      run: Start-Sleep -Seconds 10800
