name: Start Windows RDP with Ngrok

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive -Path "ngrok.zip" -DestinationPath "ngrok"

    - name: Connect Ngrok Authtoken
      run: |
        .\ngrok\ngrok.exe authtoken 2vQVdz7F82brwtpTYKFJbELmqq6_3zsmPpHoBTN7QX13u6JQ4

    - name: Enable RDP Access
      run: |
        net user runneradmin Hapis@1234
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start Ngrok Tunnel
      run: |
        Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389"
        Start-Sleep -Seconds 5

    - name: Get Ngrok RDP Address
      run: |
        $tunnels = Invoke-RestMethod http://127.0.0.1:4040/api/tunnels
        $rdpTunnel = $tunnels.tunnels | Where-Object {$_.proto -eq "tcp"}
        Write-Host "🟢 RDP Address: $($rdpTunnel.public_url)"
